import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav/NavBar";
import Footer from "@/components/Footer/Footer";
import { TranslationProvider } from "@/lib/TranslationProvider";
import DynamicMain from "@/components/DynamicMain";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Benzen App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-bg dark:bg-bg-dark text-text dark:text-text-dark antialiased`}
      >
        <TranslationProvider>
          <NavBar />
          <DynamicMain>
            {children}
            <Footer />
          </DynamicMain>
        </TranslationProvider>
      </body>
    </html>
  );
}