import { Geist, Geist_Mono, Tajawal } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav/NavBar";
import Footer from "@/components/Footer/Footer";
import DynamicMain from "@/components/DynamicMain";
import Popup from "@/components/PopUp";
import { TranslationProvider } from "react-lite-translation";
import { TRANSLATION_CONFIG } from "./lt.config";
import { modules } from "@/translations/index";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const tajawal = Tajawal({
  variable: "--font-tajawal",
  subsets: ["arabic"],
  weight: ["400", "500", "700"], 
  display: "swap",
});


export const metadata = {
  title: "Benzen App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${tajawal.variable} ${geistMono.variable} bg-bg dark:bg-bg-dark text-text dark:text-text-dark antialiased`}
      >
        <TranslationProvider  config={TRANSLATION_CONFIG}  modules={modules}>
          <Popup/>
          <NavBar />
          <DynamicMain>
            {children}
            <Footer />
          </DynamicMain>
        </TranslationProvider>
      </body>
    </html>
  );
}